<?php
declare(strict_types=1);
namespace BusinessMapLocator\Import\Duplicate;
use BusinessMapLocator\Import\Mapping\ImportMapper;
final class DuplicateDetector {
    public function __construct(private ImportMapper $mapper){}
    public function scan(): array {$locations=$this->allLocations();$groups=[];foreach($locations as $l){$fp=$this->mapper->fingerprint((string)$l['title'],(string)$l['address'],(string)$l['lat'],(string)$l['lng']);if($fp!==''){$groups[$fp][]=$l;}}$duplicates=[];$extra=0;foreach($groups as $fp=>$items){if(count($items)<2)continue;usort($items,static fn($a,$b)=>$a['id']<=>$b['id']);$duplicates[]=['fingerprint'=>$fp,'keepId'=>(int)$items[0]['id'],'items'=>$items];$extra+=count($items)-1;}return ['total'=>count($locations),'groups'=>count($duplicates),'extra'=>$extra,'duplicates'=>array_slice($duplicates,0,100)];}
    public function delete(): array {$scan=$this->scan();$deleted=0;$index=new \BML_Location_Index();do{foreach($scan['duplicates'] as $group){foreach($group['items'] as $item){$id=(int)$item['id'];if($id===(int)$group['keepId'])continue;if(wp_delete_post($id,true)){$index->delete($id);$deleted++;}}}$scan=$this->scan();}while($scan['groups']>0&&$scan['duplicates']!==[]);return ['deleted'=>$deleted]+$scan;}
    public function existingMaps(): array {$externalGroups=[];$fpGroups=[];foreach($this->allLocations() as $l){$id=(int)$l['id'];$e=(string)get_post_meta($id,'bml_external_id',true);if($e!==''){$externalGroups[$e][]=$id;}$fp=$this->mapper->fingerprint((string)$l['title'],(string)$l['address'],(string)$l['lat'],(string)$l['lng']);if($fp!==''){$fpGroups[$fp][]=$id;}}$external=$fingerprint=$ambiguousExternal=$ambiguousFingerprint=[];foreach($externalGroups as $key=>$ids){$ids=array_values(array_unique(array_map('intval',$ids)));if(count($ids)===1){$external[$key]=$ids[0];}else{$ambiguousExternal[$key]=$ids;}}foreach($fpGroups as $key=>$ids){$ids=array_values(array_unique(array_map('intval',$ids)));if(count($ids)===1){$fingerprint[$key]=$ids[0];}else{$ambiguousFingerprint[$key]=$ids;}}return compact('external','fingerprint','ambiguousExternal','ambiguousFingerprint');}
    private function allLocations(): array {$ids=get_posts(['post_type'=>'bml_location','post_status'=>['publish','draft','private'],'posts_per_page'=>-1,'fields'=>'ids','orderby'=>'ID','order'=>'ASC','no_found_rows'=>true,'update_post_meta_cache'=>true,'update_post_term_cache'=>false]);$r=[];foreach($ids as $id){$r[]=['id'=>(int)$id,'title'=>(string)get_the_title((int)$id),'address'=>(string)get_post_meta((int)$id,'bml_address',true),'lat'=>(string)get_post_meta((int)$id,'bml_lat',true),'lng'=>(string)get_post_meta((int)$id,'bml_lng',true)];}return $r;}
}
