<?php
declare(strict_types=1);
namespace BusinessMapLocator\Admin\Location\View;
if (!defined('ABSPATH')) { exit; }
final class LocationTableRenderer
{
    public function render(array $rows, bool $checkboxes): void
    {
        ?>
        <div class="bml-table-wrap"><table class="bml-table bml-locations-table" data-bml-locations-table><thead><tr><?php if ($checkboxes) : ?><th class="bml-col-check"><input type="checkbox" class="bml-check-all" aria-label="<?php esc_attr_e('Select all locations', 'business-map-locator'); ?>"></th><?php endif; ?><th><?php esc_html_e('Location', 'business-map-locator'); ?></th><th><?php esc_html_e('Classification', 'business-map-locator'); ?></th><th><?php esc_html_e('Data quality', 'business-map-locator'); ?></th><th><?php esc_html_e('Updated', 'business-map-locator'); ?></th><th><?php esc_html_e('Status', 'business-map-locator'); ?></th><th></th></tr></thead><tbody>
        <?php if (!$rows) : ?><tr><td colspan="7" class="bml-empty-cell"><div class="bml-locations-empty"><span class="dashicons dashicons-location-alt"></span><strong><?php esc_html_e('No locations found', 'business-map-locator'); ?></strong><p><?php esc_html_e('Try changing the filters or create a new location.', 'business-map-locator'); ?></p><a class="bml-btn bml-btn--primary" href="<?php echo esc_url(admin_url('admin.php?page=bml-location-edit')); ?>"><?php esc_html_e('Add location', 'business-map-locator'); ?></a></div></td></tr><?php endif; ?>
        <?php foreach ($rows as $row) :
            $searchValue = strtolower(trim(implode(' ', [$row['title'], $row['address'], $row['category'], $row['city'], $row['phone']])));
            $editUrl = admin_url('admin.php?page=bml-location-edit&id=' . $row['id']);
            $mapUrl = $row['lat'] !== null && $row['lng'] !== null ? 'https://www.openstreetmap.org/?mlat=' . rawurlencode((string) $row['lat']) . '&mlon=' . rawurlencode((string) $row['lng']) . '#map=17/' . rawurlencode((string) $row['lat']) . '/' . rawurlencode((string) $row['lng']) : '';
        ?>
            <tr data-location-search="<?php echo esc_attr($searchValue); ?>" data-status="<?php echo esc_attr($row['status']); ?>" data-quality="<?php echo esc_attr($row['quality_state']); ?>"><?php if ($checkboxes) : ?><td class="bml-col-check"><input type="checkbox" name="ids[]" value="<?php echo esc_attr((string) $row['id']); ?>"></td><?php endif; ?><td><div class="bml-location-identity"><?php echo $row['thumbnail'] !== '' ? '<span class="bml-location-identity__icon">' . wp_kses_post($row['thumbnail']) . '</span>' : '<span class="bml-location-identity__icon bml-location-identity__placeholder"><span class="dashicons dashicons-location-alt"></span></span>'; ?><span class="bml-location-identity__text"><a href="<?php echo esc_url($editUrl); ?>"><strong><?php echo esc_html($row['title']); ?></strong></a><small><?php echo esc_html($row['address'] !== '' ? $row['address'] : __('No address', 'business-map-locator')); ?></small><?php if ($row['phone'] !== '') : ?><em><span class="dashicons dashicons-phone"></span><?php echo esc_html($row['phone']); ?></em><?php endif; ?></span></div></td><td><strong class="bml-table-primary"><?php echo esc_html($row['category']); ?></strong><small class="bml-table-secondary"><?php echo esc_html($row['city']); ?></small></td><td><div class="bml-quality-cell"><span class="bml-quality-ring is-<?php echo esc_attr($row['quality_state']); ?>" style="--bml-progress:<?php echo esc_attr((string) $row['quality_percent']); ?>"><?php echo esc_html((string) $row['quality_percent']); ?>%</span><span><strong><?php echo esc_html($row['quality_label']); ?></strong><small><?php echo esc_html($row['coordinates']); ?></small></span></div></td><td><time datetime="<?php echo esc_attr($row['modified_iso']); ?>"><?php echo esc_html($row['modified_human']); ?></time></td><td><span class="bml-status-pill <?php echo $row['status'] === 'publish' ? 'is-active' : 'is-draft'; ?>"><?php echo esc_html($row['status'] === 'publish' ? __('Published', 'business-map-locator') : __('Draft', 'business-map-locator')); ?></span></td><td><div class="bml-row-primary-actions"><a href="<?php echo esc_url($editUrl); ?>"><?php esc_html_e('Edit', 'business-map-locator'); ?></a><details><summary aria-label="<?php esc_attr_e('More actions', 'business-map-locator'); ?>">⋮</summary><div class="bml-row-menu"><?php if ($mapUrl !== '') : ?><a href="<?php echo esc_url($mapUrl); ?>" target="_blank" rel="noopener"><?php esc_html_e('Open on map', 'business-map-locator'); ?></a><?php endif; ?><a href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=bml_duplicate_location&id=' . $row['id']), 'bml_duplicate_location_' . $row['id'])); ?>"><?php esc_html_e('Duplicate', 'business-map-locator'); ?></a><a class="bml-delete-link" href="<?php echo esc_url(wp_nonce_url(admin_url('admin-post.php?action=bml_delete_location&id=' . $row['id']), 'bml_delete_location_' . $row['id'])); ?>"><?php esc_html_e('Delete', 'business-map-locator'); ?></a></div></details></div></td></tr>
        <?php endforeach; ?></tbody></table></div>
        <div class="bml-locations-live-empty" data-bml-locations-empty-live hidden><span class="dashicons dashicons-search"></span><strong><?php esc_html_e('No matching locations', 'business-map-locator'); ?></strong><p><?php esc_html_e('Try another search phrase.', 'business-map-locator'); ?></p></div>
        <?php
    }
}
