<?php
declare(strict_types=1);
namespace BusinessMapLocator\Import\Job;
use BusinessMapLocator\Import\Dto\ImportJob;
use BusinessMapLocator\Import\Serialization\ImportJobPayloadSerializer;
use RuntimeException;
final class ImportJobRepository implements ImportJobRepositoryInterface {
    private string $table;
    public function __construct(?string $table=null, private ?ImportJobPayloadSerializer $serializer=null){global $wpdb;$this->table=$table??$wpdb->prefix.'bml_import_jobs';$this->serializer??=new ImportJobPayloadSerializer();}
    public static function tokenHash(string $token): string { return hash('sha256',sanitize_key($token)); }
    public function create(string $token,ImportJob $job): ImportJob { global $wpdb;$data=$job->toArray();$row=$this->toRow($data);$row['token_hash']=self::tokenHash($token);$row['version']=1;if($wpdb->insert($this->table,$row,$this->formats($row))===false){throw new RuntimeException('Unable to create the import job.');}$data['id']=(int)$wpdb->insert_id;$data['version']=1;return new ImportJob($data); }
    public function findByToken(string $token): ?ImportJob { global $wpdb;$row=$wpdb->get_row($wpdb->prepare("SELECT * FROM {$this->table} WHERE token_hash=%s LIMIT 1",self::tokenHash($token)),ARRAY_A);return is_array($row)?$this->fromRow($row):null; }
    public function find(string $token): ?ImportJob { return $this->findByToken($token); }
    public function claim(string $token,string $lockedBy,int $ttl): ?ImportJob { global $wpdb;$now=current_time('mysql',true);$until=gmdate('Y-m-d H:i:s',time()+max(15,$ttl));$sql=$wpdb->prepare("UPDATE {$this->table} SET locked_by=%s,locked_until=%s,version=version+1 WHERE token_hash=%s AND (locked_until IS NULL OR locked_until<=%s OR locked_by=%s)",$lockedBy,$until,self::tokenHash($token),$now,$lockedBy);return $wpdb->query($sql)===1?$this->findByToken($token):null; }
    public function acquireLease(string $token,string $lockedBy,int $ttl): ?ImportJob { return $this->claim($token,$lockedBy,$ttl); }
    public function releaseLease(string $token,string $lockedBy): void { global $wpdb;$wpdb->query($wpdb->prepare("UPDATE {$this->table} SET locked_by='',locked_until=NULL WHERE token_hash=%s AND locked_by=%s",self::tokenHash($token),$lockedBy)); }
    public function save(string $token,ImportJob $job,int $expectedVersion): ?ImportJob { global $wpdb;$data=$job->toArray();$row=$this->toRow($data);$row['version']=$expectedVersion+1;$set=[];$values=[];foreach($row as $column=>$value){$set[]="$column = ".$this->formatFor($value);$values[]=$value;}$values[]=self::tokenHash($token);$values[]=$expectedVersion;$updated=$wpdb->query($wpdb->prepare("UPDATE {$this->table} SET ".implode(', ',$set).' WHERE token_hash=%s AND version=%d',...$values));if($updated!==1){return null;}$data['version']=$expectedVersion+1;return new ImportJob($data); }
    public function updateAtomic(string $token,ImportJob $job,int $expectedVersion): ?ImportJob { return $this->save($token,$job,$expectedVersion); }
    public function cancel(string $token,ImportJob $job,int $expectedVersion): ?ImportJob { $job['status']=ImportJobStatus::CANCELLED->value;$job['path']='';return $this->save($token,$job,$expectedVersion); }
    public function findExpired(int $limit=100): array { global $wpdb;$limit=max(1,min(500,$limit));$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$this->table} WHERE expires_at<=%s ORDER BY expires_at ASC LIMIT %d",current_time('mysql',true),$limit),ARRAY_A);return is_array($rows)?array_map(fn(array $r):ImportJob=>$this->fromRow($r),$rows):[]; }
    public function expired(int $limit=100): array { return $this->findExpired($limit); }
    public function deleteExpired(int $limit=100): int { global $wpdb;$count=0;foreach($this->findExpired($limit) as $job){$id=(int)$job['id'];$deleted=$wpdb->delete($this->table,['id'=>$id],['%d']);if($deleted===1){$count++;}}return $count; }
    public function listByOwner(int $ownerUserId,int $limit=50,int $offset=0): array { global $wpdb;$rows=$wpdb->get_results($wpdb->prepare("SELECT * FROM {$this->table} WHERE owner_user_id=%d ORDER BY id DESC LIMIT %d OFFSET %d",$ownerUserId,max(1,min(200,$limit)),max(0,$offset)),ARRAY_A);return is_array($rows)?array_map(fn(array $r):ImportJob=>$this->fromRow($r),$rows):[]; }
    public function deleteById(int $id): void { global $wpdb;$wpdb->delete($this->table,['id'=>$id],['%d']); }
    public function activeFilePaths(): array { global $wpdb;$active=implode(',',array_map(static fn(ImportJobStatus $s):string=>"'".$s->value."'",array_filter(ImportJobStatus::cases(),static fn(ImportJobStatus $s):bool=>$s->keepsFileActive())));$rows=$wpdb->get_col("SELECT file_path FROM {$this->table} WHERE file_path<>'' AND status IN ({$active})");return is_array($rows)?array_map('strval',$rows):[]; }
    private function toRow(array $job): array { $payload=$job;foreach(['id','version','token','ownerUserId','path','status','position','readPosition','committedPosition','total','processed','readRows','committedRows','added','updated','skipped','processingErrors','inspectionErrors','dryRun','lockedBy','lockedUntil','startedAt','updatedAt','expiresAt','headers'] as $key){unset($payload[$key]);}return ['owner_user_id'=>(int)($job['ownerUserId']??0),'status'=>(string)($job['status']??'prepared'),'file_path'=>(string)($job['path']??''),'headers_json'=>$this->serializer->encode(['headers'=>(array)($job['headers']??[])]),'position'=>(int)($job['committedPosition']??$job['position']??0),'read_position'=>(int)($job['readPosition']??$job['position']??0),'committed_position'=>(int)($job['committedPosition']??$job['position']??0),'total_rows'=>(int)($job['total']??0),'processed_rows'=>(int)($job['committedRows']??$job['processed']??0),'read_rows'=>(int)($job['readRows']??$job['processed']??0),'committed_rows'=>(int)($job['committedRows']??$job['processed']??0),'created_rows'=>(int)($job['added']??0),'updated_rows'=>(int)($job['updated']??0),'skipped_rows'=>(int)($job['skipped']??0),'error_rows'=>(int)($job['processingErrors']??0),'inspection_errors'=>(int)($job['inspectionErrors']??0),'dry_run'=>!empty($job['dryRun'])?1:0,'payload_json'=>$this->serializer->encode($payload),'locked_by'=>(string)($job['lockedBy']??''),'locked_until'=>!empty($job['lockedUntil'])?(string)$job['lockedUntil']:null,'started_at'=>$this->mysqlDate($job['startedAt']??null),'updated_at'=>$this->mysqlDate($job['updatedAt']??null),'expires_at'=>gmdate('Y-m-d H:i:s',(int)($job['expiresAt']??time()))]; }
    private function fromRow(array $row): ImportJob { $payload=$this->serializer->decode((string)($row['payload_json']??''));$headersDecoded=$this->serializer->decode((string)($row['headers_json']??''));$headers=(array)($headersDecoded['headers']??[]);if($headers===[]){$legacy=json_decode((string)($row['headers_json']??'[]'),true);$headers=is_array($legacy)?$legacy:[];}$payload += ['id'=>(int)$row['id'],'version'=>(int)$row['version'],'ownerUserId'=>(int)$row['owner_user_id'],'path'=>(string)$row['file_path'],'headers'=>$headers,'status'=>(string)$row['status'],'position'=>(int)($row['committed_position']??$row['position']??0),'readPosition'=>(int)($row['read_position']??$row['position']??0),'committedPosition'=>(int)($row['committed_position']??$row['position']??0),'total'=>(int)$row['total_rows'],'processed'=>(int)($row['committed_rows']??$row['processed_rows']??0),'readRows'=>(int)($row['read_rows']??$row['processed_rows']??0),'committedRows'=>(int)($row['committed_rows']??$row['processed_rows']??0),'added'=>(int)$row['created_rows'],'updated'=>(int)$row['updated_rows'],'skipped'=>(int)$row['skipped_rows'],'processingErrors'=>(int)$row['error_rows'],'inspectionErrors'=>(int)$row['inspection_errors'],'dryRun'=>(bool)$row['dry_run'],'lockedBy'=>(string)($row['locked_by']??''),'lockedUntil'=>(string)($row['locked_until']??''),'startedAt'=>(string)$row['started_at'],'updatedAt'=>(string)$row['updated_at'],'expiresAt'=>strtotime((string)$row['expires_at'])?:0];return new ImportJob($payload); }
    private function mysqlDate(mixed $v): string { return is_string($v)&&$v!==''?$v:current_time('mysql',true); }
    private function formats(array $r): array { return array_map(fn(mixed $v):string=>$this->formatFor($v),$r); }
    private function formatFor(mixed $v): string { return is_int($v)?'%d':'%s'; }
}
