<?php
declare(strict_types=1);
namespace BusinessMapLocator\Migration;
/** Control-plane owner only. Taxonomy, meta, and index writes belong to later execution slices. */
final class AreaMigrationExecutor
{
    public function __construct(private readonly MigrationSnapshotStore $snapshots, private readonly AreaMigrationStateStore $state, private readonly AreaMigrationLock $lock, private readonly AreaMigrationJournal $journal, private readonly AreaMigrationRevalidator $revalidator) {}
    /** @return array<string,mixed> */ public function inspectEligibility(string $runId): array { $run=$this->state->get($runId);if($run===null)return $this->blocked('RUN_NOT_FOUND');$snapshot=$this->snapshot($run);if($snapshot===null)return $this->blocked('SNAPSHOT_UNAVAILABLE',$run);if(($snapshot['schema_version']??null)!==2)return $this->blocked('SNAPSHOT_VERSION_UNSUPPORTED',$run,$snapshot);if(($run['state']??null)!==AreaMigrationStateStore::READY)return $this->blocked('RUN_NOT_READY',$run,$snapshot);if(!$this->hasPlanEvidence($snapshot))return $this->blocked('PLANNING_EVIDENCE_MISSING',$run,$snapshot);if($this->hasBlockers($snapshot))return $this->blocked('PLANNER_BLOCKERS_PRESENT',$run,$snapshot);if(!$this->ownsLock($runId))return $this->blocked('LOCK_NOT_OWNED',$run,$snapshot);$drift=$this->revalidator->inspect($snapshot);if(!$drift['valid'])return $this->blocked('DRIFT_DETECTED',$run,$snapshot,$drift);return $this->result(true,'ELIGIBLE',$run,$snapshot,$drift); }
    /** @return array<string,mixed> */ public function beginTermPhase(string $runId): array { $result=$this->inspectEligibility($runId);if(!$result['eligible'])return $result;$run=$this->state->transition($runId,AreaMigrationStateStore::RUNNING_TERMS,['execution_phase'=>'terms_entered_at_'.gmdate('c')]);return $this->result(true,'TERM_PHASE_ENTERED',$run,$this->snapshot($run)??[],$result['drift']); }
    /** @return array<string,mixed> */ public function beginRelationshipPhase(string $runId): array { $run=$this->state->get($runId);if($run===null||($run['state']??null)!==AreaMigrationStateStore::RUNNING_TERMS||!$this->ownsLock($runId))return $this->blocked('RELATIONSHIP_PHASE_NOT_ALLOWED',$run??[]);return $this->result(true,'RELATIONSHIP_PHASE_ENTERED',$this->state->transition($runId,AreaMigrationStateStore::RUNNING_RELATIONSHIPS),$this->snapshot($run)??[],['valid'=>true,'drift'=>[],'summary'=>['count'=>0]]); }
    /** @param array<string,mixed> $run @return array<string,mixed>|null */ private function snapshot(array $run): ?array { return isset($run['snapshot_path'])&&is_string($run['snapshot_path'])?$this->snapshots->read($run['snapshot_path']):null; }
    /** @param array<string,mixed> $snapshot */ private function hasPlanEvidence(array $snapshot): bool { return is_array($snapshot['plan']??null)&&is_array($snapshot['plan']['counts']??null); }
    /** @param array<string,mixed> $snapshot */ private function hasBlockers(array $snapshot): bool { $plan=(array)($snapshot['plan']??[]);return !empty($plan['collision_list'])||!empty($plan['ambiguous_list'])||!empty($plan['decision_required_list']); }
    private function ownsLock(string $runId): bool { $owner=$this->lock->owner();return $this->lock->isLocked()&&$owner!==null&&(string)$owner['run_id']===$runId; }
    /** @param array<string,mixed> $run @param array<string,mixed> $snapshot @param array<string,mixed>|null $drift @return array<string,mixed> */ private function blocked(string $code,array $run=[],array $snapshot=[],?array $drift=null): array { return $this->result(false,$code,$run,$snapshot,$drift??['valid'=>null,'drift'=>[],'summary'=>['count'=>0]]); }
    /** @param array<string,mixed> $run @param array<string,mixed> $snapshot @param array<string,mixed> $drift @return array<string,mixed> */ private function result(bool $eligible,string $code,array $run,array $snapshot,array $drift): array { $runId=(string)($run['run_id']??'');$operations=$runId===''?[]:$this->journal->listRunOperations($runId);return ['eligible'=>$eligible,'blocked'=>!$eligible,'code'=>$code,'run_state'=>$run['state']??null,'snapshot_version'=>$snapshot['schema_version']??null,'lock'=>['owned_by_run'=>$runId!==''&&$this->ownsLock($runId),'owner'=>$this->lock->owner()],'journal'=>['available'=>true,'operations'=>count($operations),'incomplete'=>count($runId===''?[]:$this->journal->listIncompleteOperations($runId))],'plan_summary'=>$snapshot['plan']['counts']??[],'drift'=>$drift]; }
}
