<?php
declare(strict_types=1);
namespace BusinessMapLocator\Migration;
/** Read-only comparison of snapshot evidence with current taxonomy state. */
final class AreaMigrationRevalidator
{
    /** @param array<string,mixed> $snapshot @return array<string,mixed> */ public function inspect(array $snapshot): array { $drift=[]; foreach ((array)($snapshot['terms']['bml_city']??[]) as $city) $drift=array_merge($drift,$this->termDrift('city',$city,$this->term((int)($city['id']??0),'bml_city'),['name','slug','parent'])); foreach ((array)($snapshot['terms']['bml_area']??[]) as $area) $drift=array_merge($drift,$this->termDrift('area',$area,$this->term((int)($area['id']??0),'bml_area'),['name','slug','parent','migrated_from_city_term_id'])); foreach ((array)($snapshot['locations']??[]) as $location) { $id=(int)($location['location_id']??0);$city=$this->termIds($id,'bml_city');$area=$this->termIds($id,'bml_area');$expectedCity=$this->ids($location['city_ids']??[]);$expectedArea=$this->ids($location['area_ids']??[]);if($city!==$expectedCity)$drift[]=['code'=>'LOCATION_CITY_CHANGED','location_id'=>$id,'expected'=>$expectedCity,'actual'=>$city];if(count($city)>1)$drift[]=['code'=>'LOCATION_SECOND_CITY','location_id'=>$id,'actual'=>$city];if($area!==$expectedArea)$drift[]=['code'=>'LOCATION_AREA_CHANGED','location_id'=>$id,'expected'=>$expectedArea,'actual'=>$area];if($expectedArea===[]&&$area!==[])$drift[]=['code'=>'LOCATION_UNRELATED_AREA','location_id'=>$id,'actual'=>$area]; } return ['valid'=>$drift===[],'drift'=>$drift,'summary'=>['count'=>count($drift)]]; }
    /** @return array<string,mixed>|null */ private function term(int $id,string $taxonomy): ?array { foreach ((array)get_terms(['taxonomy'=>$taxonomy,'hide_empty'=>false,'number'=>0]) as $term) if((int)$term->term_id===$id)return ['id'=>$id,'name'=>(string)$term->name,'slug'=>(string)$term->slug,'parent'=>(int)$term->parent,'migrated_from_city_term_id'=>(int)get_term_meta($id,'_bml_migrated_from_city_term_id',true)];return null; }
    /** @param array<string,mixed> $expected @param array<string,mixed>|null $actual @param list<string> $keys @return list<array<string,mixed>> */ private function termDrift(string $kind,array $expected,?array $actual,array $keys): array { if($actual===null)return [['code'=>strtoupper($kind).'_MISSING','term_id'=>(int)($expected['id']??0)]];$drift=[];foreach($keys as $key)if(array_key_exists($key,$expected)&&$expected[$key]!==$actual[$key])$drift[]=['code'=>strtoupper($kind).'_IDENTITY_CHANGED','term_id'=>(int)$expected['id'],'field'=>$key,'expected'=>$expected[$key],'actual'=>$actual[$key]];return $drift; }
    /** @param mixed $ids @return list<int> */ private function ids(mixed $ids): array { $ids=is_array($ids)?array_map('intval',$ids):[];sort($ids,SORT_NUMERIC);return array_values(array_unique($ids)); }
    /** @return list<int> */ private function termIds(int $id,string $taxonomy): array { $terms=wp_get_post_terms($id,$taxonomy,['fields'=>'ids']);return $this->ids(is_array($terms)?$terms:[]); }
}
