<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
use BusinessMapLocator\Migration\{AreaMigrationExecutor,AreaMigrationJournal,AreaMigrationLock,AreaMigrationRevalidator,AreaMigrationStateStore,AreaRollbackService,MigrationSnapshotStore};
final class AreaMigrationExecutionControlPlaneTest extends TestCase
{
    private string $dir;
    protected function setUp(): void { $this->dir=dirname(__DIR__).'/.execution-fixture-'.bin2hex(random_bytes(4));mkdir($this->dir,0777,true);$GLOBALS['bml_test_options']=[];$GLOBALS['bml_test_terms']=[];$GLOBALS['bml_test_term_meta']=[];$GLOBALS['bml_test_posts']=[];$GLOBALS['bml_test_post_terms']=[]; }
    protected function tearDown(): void { $items=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($this->dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($items as $item)$item->isDir()?rmdir($item->getPathname()):unlink($item->getPathname());rmdir($this->dir); }
    /** @return array{0:AreaMigrationStateStore,1:MigrationSnapshotStore,2:AreaMigrationLock,3:AreaMigrationJournal,4:AreaMigrationExecutor,5:AreaRollbackService} */ private function services(): array { $suffix=bin2hex(random_bytes(4));$s=new AreaMigrationStateStore();$store=new MigrationSnapshotStore($this->dir.'/snapshots-'.$suffix);$lock=new AreaMigrationLock();$journal=new AreaMigrationJournal($this->dir.'/journal-'.$suffix);$revalidator=new AreaMigrationRevalidator();return [$s,$store,$lock,$journal,new AreaMigrationExecutor($store,$s,$lock,$journal,$revalidator),new AreaRollbackService($store,$s,$lock,$journal,$revalidator)]; }
    /** @return array<string,mixed> */ private function snapshot(int $version=2): array { return ['schema_version'=>$version,'migration'=>'bml_city_to_area_v1','created_at'=>'2026-01-01T00:00:00Z','created_by_user_id'=>1,'ownership'=>['site_url'=>'x','plugin_version'=>'x','wp_version'=>'x','php_version'=>'x','created_at'=>'x','created_by_user_id'=>1],'taxonomies'=>['bml_city','bml_area'],'terms'=>['bml_city'=>[['id'=>1,'name'=>'Minsk','slug'=>'minsk','parent'=>0]],'bml_area'=>[]],'locations'=>[['location_id'=>7,'city_ids'=>[1],'area_ids'=>[]]],'plan'=>['counts'=>['cities'=>[],'locations'=>[]],'collision_list'=>[],'ambiguous_list'=>[],'decision_required_list'=>[]]]; }
    private function fixtureReady(int $version=2): array { [$s,$store,$lock,$journal,$executor,$rollback]=$this->services();$term=(object)['term_id'=>1,'name'=>'Minsk','slug'=>'minsk','parent'=>0];$GLOBALS['bml_test_terms']=['bml_city'=>[1=>$term],'bml_area'=>[]];$post=new WP_Post();$post->ID=7;$post->post_type='bml_location';$post->post_status='publish';$GLOBALS['bml_test_posts']=[7=>$post];$GLOBALS['bml_test_post_terms']=[7=>['bml_city'=>[1],'bml_area'=>[]]];$path=$store->write($this->snapshot($version));$run=$s->create();foreach([AreaMigrationStateStore::INSPECTED,AreaMigrationStateStore::SNAPSHOTTED,AreaMigrationStateStore::SIMULATED,AreaMigrationStateStore::READY] as $next)$run=$s->transition($run['run_id'],$next,$next===AreaMigrationStateStore::SNAPSHOTTED?['snapshot_path'=>$path]:[]);return [$s,$store,$lock,$journal,$executor,$rollback,$run]; }
    public function testExecutionAndRollbackStateTransitionsRejectInvalidPaths(): void { $s=new AreaMigrationStateStore();$run=$s->create();$this->expectException(LogicException::class);$s->transition($run['run_id'],AreaMigrationStateStore::RUNNING_TERMS); }
    public function testRepresentativeInvalidExecutionAndRollbackTransitionsAreRejected(): void { $s=new AreaMigrationStateStore();$new=$s->create();$this->assertTransitionRejected($s,$new,AreaMigrationStateStore::RUNNING_TERMS);$simulated=$s->create();foreach([AreaMigrationStateStore::INSPECTED,AreaMigrationStateStore::SNAPSHOTTED,AreaMigrationStateStore::SIMULATED] as $next)$simulated=$s->transition($simulated['run_id'],$next);$this->assertTransitionRejected($s,$simulated,AreaMigrationStateStore::RUNNING_TERMS);$ready=$s->transition($simulated['run_id'],AreaMigrationStateStore::READY);$this->assertTransitionRejected($s,$ready,AreaMigrationStateStore::COMPLETED);$completed=$s->transition($ready['run_id'],AreaMigrationStateStore::RUNNING_TERMS);$completed=$s->transition($completed['run_id'],AreaMigrationStateStore::RUNNING_RELATIONSHIPS);$completed=$s->transition($completed['run_id'],AreaMigrationStateStore::COMPLETED);$this->assertTransitionRejected($s,$completed,AreaMigrationStateStore::RUNNING_TERMS);$rolledBack=$s->transition($completed['run_id'],AreaMigrationStateStore::ROLLBACK_RUNNING);$rolledBack=$s->transition($rolledBack['run_id'],AreaMigrationStateStore::ROLLED_BACK);$this->assertTransitionRejected($s,$rolledBack,AreaMigrationStateStore::RUNNING_TERMS);$this->assertTransitionRejected($s,$rolledBack,AreaMigrationStateStore::ROLLBACK_RUNNING); }
    public function testAllNewExecutionAndRollbackTransitionsAreExplicit(): void { $s=new AreaMigrationStateStore();$r=$s->create();foreach([AreaMigrationStateStore::INSPECTED,AreaMigrationStateStore::SNAPSHOTTED,AreaMigrationStateStore::SIMULATED,AreaMigrationStateStore::READY,AreaMigrationStateStore::RUNNING_TERMS,AreaMigrationStateStore::RUNNING_RELATIONSHIPS,AreaMigrationStateStore::COMPLETED,AreaMigrationStateStore::ROLLBACK_RUNNING,AreaMigrationStateStore::ROLLED_BACK] as $next)$r=$s->transition($r['run_id'],$next);$this->assertSame(AreaMigrationStateStore::ROLLED_BACK,$r['state']);$this->expectException(LogicException::class);$s->transition($r['run_id'],AreaMigrationStateStore::RUNNING_TERMS); }
    public function testInterruptionAndRollbackTerminalTransitionsAreExplicit(): void { $s=new AreaMigrationStateStore();foreach([[AreaMigrationStateStore::RUNNING_TERMS,AreaMigrationStateStore::PARTIAL],[AreaMigrationStateStore::RUNNING_TERMS,AreaMigrationStateStore::FAILED],[AreaMigrationStateStore::RUNNING_TERMS,AreaMigrationStateStore::BLOCKED],[AreaMigrationStateStore::RUNNING_RELATIONSHIPS,AreaMigrationStateStore::PARTIAL],[AreaMigrationStateStore::RUNNING_RELATIONSHIPS,AreaMigrationStateStore::FAILED],[AreaMigrationStateStore::RUNNING_RELATIONSHIPS,AreaMigrationStateStore::BLOCKED]] as [$phase,$terminal]){$r=$s->create();foreach([AreaMigrationStateStore::INSPECTED,AreaMigrationStateStore::SNAPSHOTTED,AreaMigrationStateStore::SIMULATED,AreaMigrationStateStore::READY,AreaMigrationStateStore::RUNNING_TERMS] as $next)$r=$s->transition($r['run_id'],$next);if($phase===AreaMigrationStateStore::RUNNING_RELATIONSHIPS)$r=$s->transition($r['run_id'],$phase);$this->assertSame($terminal,$s->transition($r['run_id'],$terminal)['state']);}$r=$s->create();foreach([AreaMigrationStateStore::INSPECTED,AreaMigrationStateStore::SNAPSHOTTED,AreaMigrationStateStore::SIMULATED,AreaMigrationStateStore::READY,AreaMigrationStateStore::RUNNING_TERMS,AreaMigrationStateStore::RUNNING_RELATIONSHIPS,AreaMigrationStateStore::COMPLETED,AreaMigrationStateStore::ROLLBACK_RUNNING] as $next)$r=$s->transition($r['run_id'],$next);$this->assertSame(AreaMigrationStateStore::ROLLBACK_PARTIAL,$s->transition($r['run_id'],AreaMigrationStateStore::ROLLBACK_PARTIAL)['state']);$r=$s->create();foreach([AreaMigrationStateStore::INSPECTED,AreaMigrationStateStore::SNAPSHOTTED,AreaMigrationStateStore::SIMULATED,AreaMigrationStateStore::READY,AreaMigrationStateStore::RUNNING_TERMS,AreaMigrationStateStore::RUNNING_RELATIONSHIPS,AreaMigrationStateStore::COMPLETED,AreaMigrationStateStore::ROLLBACK_RUNNING] as $next)$r=$s->transition($r['run_id'],$next);$r=$s->transition($r['run_id'],AreaMigrationStateStore::FAILED);$this->assertSame(AreaMigrationStateStore::ROLLBACK_RUNNING,$s->transition($r['run_id'],AreaMigrationStateStore::ROLLBACK_RUNNING)['state']); }
    public function testV1SnapshotIsRefusedWithoutStateTransition(): void { [$s,$unusedStore,$unusedLock,$unusedJournal,$executor,$unusedRollback,$run]=$this->fixtureReady(1);$this->assertSame('SNAPSHOT_VERSION_UNSUPPORTED',$executor->inspectEligibility($run['run_id'])['code']);$this->assertSame(AreaMigrationStateStore::READY,$s->get($run['run_id'])['state']); }
    public function testReadyRunWithSameRunLockIsEligibleAndOnlyEntersTermState(): void { [$s,$unusedStore,$lock,$unusedJournal,$executor,$unusedRollback,$run]=$this->fixtureReady();$before=serialize([$GLOBALS['bml_test_terms'],$GLOBALS['bml_test_term_meta'],$GLOBALS['bml_test_post_terms']]);$this->assertTrue($lock->acquire($run['run_id']));$this->assertTrue($executor->inspectEligibility($run['run_id'])['eligible']);$result=$executor->beginTermPhase($run['run_id']);$this->assertSame('TERM_PHASE_ENTERED',$result['code']);$this->assertSame(AreaMigrationStateStore::RUNNING_TERMS,$s->get($run['run_id'])['state']);$this->assertSame($before,serialize([$GLOBALS['bml_test_terms'],$GLOBALS['bml_test_term_meta'],$GLOBALS['bml_test_post_terms']])); }
    public function testInitialPreflightRejectsWrongStatesAndCompetingLock(): void { [$s,, $lock,, $executor,, $run]=$this->fixtureReady();foreach([AreaMigrationStateStore::NEW,AreaMigrationStateStore::SIMULATED,AreaMigrationStateStore::COMPLETED,AreaMigrationStateStore::ROLLED_BACK] as $state){$copy=$s->create();$GLOBALS['bml_test_options']['bml_area_migration_planning_runs'][$copy['run_id']]=array_merge($run,['run_id'=>$copy['run_id'],'state'=>$state]);$this->assertFalse($executor->inspectEligibility($copy['run_id'])['eligible']);}$this->assertTrue($lock->acquire('competing'));$this->assertFalse($lock->acquire($run['run_id']));$this->assertFalse($lock->release($run['run_id']));$this->assertTrue($lock->release('competing')); }
    public function testRevalidationReportsRepresentativeDriftWithoutWrites(): void { [$unusedState,$unusedStore,$lock,$unusedJournal,$executor,$unusedRollback,$run]=$this->fixtureReady();$this->assertTrue($lock->acquire($run['run_id']));unset($GLOBALS['bml_test_terms']['bml_city'][1]);$result=$executor->inspectEligibility($run['run_id']);$this->assertSame('DRIFT_DETECTED',$result['code']);$this->assertSame('CITY_MISSING',$result['drift']['drift'][0]['code']); }
    public function testRevalidationObservesIdentityProvenanceAndLocationDrift(): void { $snapshot=$this->snapshot();$snapshot['terms']['bml_area']=[['id'=>2,'name'=>'Minsk area','slug'=>'minsk-area','parent'=>0,'migrated_from_city_term_id'=>1]];$snapshot['locations'][0]['area_ids']=[2];$snapshot['locations'][]=['location_id'=>8,'city_ids'=>[],'area_ids'=>[]];$city=(object)['term_id'=>1,'name'=>'Changed','slug'=>'minsk','parent'=>0];$area=(object)['term_id'=>2,'name'=>'Minsk area','slug'=>'minsk-area','parent'=>0];$GLOBALS['bml_test_terms']=['bml_city'=>[1=>$city],'bml_area'=>[2=>$area]];$GLOBALS['bml_test_term_meta']=[2=>['_bml_migrated_from_city_term_id'=>9]];$GLOBALS['bml_test_post_terms']=[7=>['bml_city'=>[1,3],'bml_area'=>[2,4]],8=>['bml_city'=>[],'bml_area'=>[4]]];$codes=array_column((new AreaMigrationRevalidator())->inspect($snapshot)['drift'],'code');$this->assertContains('CITY_IDENTITY_CHANGED',$codes);$this->assertContains('AREA_IDENTITY_CHANGED',$codes);$this->assertContains('LOCATION_SECOND_CITY',$codes);$this->assertContains('LOCATION_AREA_CHANGED',$codes);$this->assertContains('LOCATION_UNRELATED_AREA',$codes); }
    public function testRollbackPreflightRequiresV2EvidenceAndAllowsExplicitEntry(): void { [$s,, $lock,$journal,, $rollback,$run]=$this->fixtureReady();$this->assertTrue($lock->acquire($run['run_id']));$s->transition($run['run_id'],AreaMigrationStateStore::RUNNING_TERMS);$s->transition($run['run_id'],AreaMigrationStateStore::RUNNING_RELATIONSHIPS);$s->transition($run['run_id'],AreaMigrationStateStore::COMPLETED);$op=$journal->planOperation($run['run_id'],2,'CREATE_AREA',['city_term_id'=>1]);$this->assertTrue($rollback->inspectEligibility($run['run_id'])['eligible']);$result=$rollback->beginRollback($run['run_id']);$this->assertSame('ROLLBACK_PHASE_ENTERED',$result['code']);$this->assertSame(AreaMigrationStateStore::ROLLBACK_RUNNING,$s->get($run['run_id'])['state']);$this->assertNotEmpty($op); }
    public function testRollbackRefusesReadyAndV1Runs(): void { [$s,$store,$lock,$journal,$executor,$rollback,$run]=$this->fixtureReady();$this->assertTrue($lock->acquire($run['run_id']));$this->assertSame('RUN_NOT_ROLLBACK_ELIGIBLE',$rollback->inspectEligibility($run['run_id'])['code']);$this->assertTrue($lock->release($run['run_id']));[$v1state,$v1store,$v1lock,$v1journal,$v1executor,$v1rollback,$v1run]=$this->fixtureReady(1);$this->assertTrue($v1lock->acquire($v1run['run_id']));$this->assertSame('SNAPSHOT_VERSION_UNSUPPORTED',$v1rollback->inspectEligibility($v1run['run_id'])['code']); }
    public function testRollbackControlPlaneHasNoWordPressMutationCalls(): void { $source=file_get_contents(dirname(__DIR__).'/src/Migration/AreaRollbackService.php');foreach(['wp_insert_term','wp_update_term','wp_delete_term','wp_set_object_terms','wp_remove_object_terms','update_term_meta','delete_term_meta'] as $forbidden)$this->assertStringNotContainsString($forbidden.'(',$source); }
    /** @param array<string,mixed> $run */ private function assertTransitionRejected(AreaMigrationStateStore $state,array $run,string $next): void { try{$state->transition($run['run_id'],$next);$this->fail('Transition should be rejected.');}catch(LogicException){$this->addToAssertionCount(1);} }
}
