<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
use BusinessMapLocator\Migration\{AreaMigrationPlanner,AreaMigrationStateStore,AreaMigrationLock,AreaMigrationService,MigrationSnapshotStore};
final class AreaMigrationPlanningFoundationTest extends TestCase
{
    protected function setUp(): void { $GLOBALS['bml_test_options']=[];$GLOBALS['bml_test_terms']=[];$GLOBALS['bml_test_term_meta']=[];$GLOBALS['bml_test_posts']=[];$GLOBALS['bml_test_post_terms']=[]; }
    private function city(int $id=1): array { return ['id'=>$id,'name'=>'Minsk','slug'=>'minsk','area_term_id'=>0]; }
    private function area(int $id=2): array { return ['id'=>$id,'name'=>'Minsk','slug'=>'minsk','migrated_from_city_term_id'=>0]; }
    public function testDecisionMatrixIsNonAuthoritativeForSlugAndName(): void { $p=new AreaMigrationPlanner();$this->assertSame('CREATE',$p->decide($this->city(),[])['status']);$a=$this->area();$a['migrated_from_city_term_id']=1;$this->assertSame('ALREADY_MAPPED',$p->decide(array_merge($this->city(),['area_term_id'=>2]),[$a])['status']);$this->assertSame('COLLISION',$p->decide($this->city(),[$this->area()])['status']);$this->assertSame('REQUIRES_DECISION',$p->decide(array_merge($this->city(),['area_term_id'=>2]),[$this->area()])['status']);$this->assertSame('REQUIRES_DECISION',$p->decide($this->city(),[$a])['status']);$this->assertSame('AMBIGUOUS',$p->decide($this->city(),[$this->area(),array_merge($this->area(3),['slug'=>'other'])])['status']); }
    public function testLocationPlanPreservesExistingAreaAndIncludesDraft(): void { $p=new AreaMigrationPlanner();$d=[1=>['status'=>'CREATE','planned_area'=>['name'=>'Minsk','slug'=>'minsk','parent'=>0]],2=>['status'=>'ALREADY_MAPPED','target_area_id'=>8]];$plan=$p->planLocations([['location_id'=>1,'post_status'=>'publish','city_ids'=>[],'area_ids'=>[]],['location_id'=>2,'post_status'=>'draft','city_ids'=>[1],'area_ids'=>[]],['location_id'=>3,'post_status'=>'publish','city_ids'=>[2],'area_ids'=>[8]],['location_id'=>4,'post_status'=>'publish','city_ids'=>[1,2],'area_ids'=>[]],['location_id'=>5,'post_status'=>'publish','city_ids'=>[1],'area_ids'=>[9]]],$d);$this->assertSame('UNCHANGED',$plan['records'][0]['status']);$this->assertSame('ADD_AREA',$plan['records'][1]['status']);$this->assertSame('draft',$plan['records'][1]['post_status']);$this->assertSame('NOOP',$plan['records'][2]['status']);$this->assertSame('REQUIRES_DECISION',$plan['records'][3]['status']);$this->assertSame('REQUIRES_DECISION',$plan['records'][4]['status']); }
    public function testStateTransitionsAreDurableAndValidated(): void { $s=new AreaMigrationStateStore();$run=$s->create();$this->assertSame('NEW',$run['state']);$run=$s->transition($run['run_id'],'INSPECTED');$this->assertSame('INSPECTED',$s->get($run['run_id'])['state']);$this->expectException(LogicException::class);$s->transition($run['run_id'],'READY'); }
    public function testLockRejectsFreshOwnerAndRecoversStaleLock(): void { $l=new AreaMigrationLock();$this->assertTrue($l->acquire('a',30));$this->assertFalse($l->acquire('b',30));$this->assertFalse($l->release('b'));$this->assertTrue($l->release('a'));$GLOBALS['bml_test_options']['bml_area_migration_planning_lock']=['run_id'=>'old','expires_at'=>time()-1];$this->assertFalse($l->isLocked());$this->assertTrue($l->acquire('fresh',30));$this->assertSame('fresh',$l->owner()['run_id']); }
    public function testSimulationDoesNotExposeApplyCapability(): void { $this->assertFalse(method_exists(AreaMigrationService::class,'apply'));$this->assertFalse(method_exists(AreaMigrationService::class,'execute'));$this->assertFalse(method_exists(AreaMigrationService::class,'rollback'));$this->assertFalse(method_exists(AreaMigrationPlanner::class,'apply')); }
    public function testSnapshotValidationKeepsV1DiagnosticCompatibilityButRequiresV2Evidence(): void { $store=new MigrationSnapshotStore(sys_get_temp_dir());$base=['migration'=>'bml_city_to_area_v1','created_at'=>'2026-01-01T00:00:00Z','created_by_user_id'=>1,'ownership'=>['site_url'=>'x','plugin_version'=>'x','wp_version'=>'x','php_version'=>'x','created_at'=>'x','created_by_user_id'=>1],'taxonomies'=>['bml_city','bml_area'],'terms'=>[]];$this->assertTrue($store->validate(array_merge($base,['schema_version'=>1]))['valid']);$this->assertFalse($store->validate(array_merge($base,['schema_version'=>2]))['valid']);$this->assertTrue($store->validate(array_merge($base,['schema_version'=>2,'locations'=>[],'plan'=>[]]))['valid']); }
    public function testSimulationDoesNotAlterTermOrRelationshipFixtures(): void { $term=(object)['term_id'=>1,'name'=>'Minsk','slug'=>'minsk','parent'=>0,'count'=>1];$GLOBALS['bml_test_terms']=['bml_city'=>[1=>$term],'bml_area'=>[]];$post=new WP_Post();$post->ID=7;$post->post_type='bml_location';$post->post_status='draft';$GLOBALS['bml_test_posts']=[7=>$post];$GLOBALS['bml_test_post_terms']=[7=>['bml_city'=>[1],'bml_area'=>[]]];$before=serialize([$GLOBALS['bml_test_terms'],$GLOBALS['bml_test_post_terms']]);$simulation=(new AreaMigrationService(new MigrationSnapshotStore(sys_get_temp_dir())))->simulateMigration();$this->assertSame(1,$simulation['plan']['counts']['cities']['CREATE']);$this->assertSame(1,$simulation['plan']['counts']['locations']['ADD_AREA']);$this->assertSame($before,serialize([$GLOBALS['bml_test_terms'],$GLOBALS['bml_test_post_terms']])); }
}
