<?php
declare(strict_types=1);

use BusinessMapLocator\Import\Dto\ImportJob;
use BusinessMapLocator\Import\Mapping\ImportMapper;
use BusinessMapLocator\Import\Processing\LocationImporter;
use PHPUnit\Framework\TestCase;

final class CsvAreaImportTest extends TestCase
{
    protected function setUp(): void
    {
        $GLOBALS['bml_test_posts']=[];$GLOBALS['bml_test_meta']=[];$GLOBALS['bml_test_post_terms']=[];$GLOBALS['bml_test_relation_index_rows']=[];$GLOBALS['bml_test_indexed']=[];$GLOBALS['bml_test_term_meta']=[];
        $GLOBALS['bml_test_terms']=['bml_area'=>[1=>$this->term(1,'Area A','area-a'),2=>$this->term(2,'Area B','area-b'),3=>$this->term(3,'Parent','parent'),4=>$this->term(4,'Child','child',3),5=>$this->term(5,'Inactive','inactive')],'bml_city'=>[10=>$this->term(10,'City A','city-a'),11=>$this->term(11,'City B','city-b'),12=>$this->term(12,'Minsk','minsk')],'bml_category'=>[20=>$this->term(20,'Shop','shop')]];
        $GLOBALS['bml_test_term_meta']=[10=>['_bml_area_term_id'=>1],1=>['_bml_migrated_from_city_term_id'=>10],11=>['_bml_area_term_id'=>2],2=>['_bml_migrated_from_city_term_id'=>11],5=>['bml_area_active'=>'0']];
    }
    public function testHeaderRecognizesAreaWithoutAreaPath(): void {$mapper=new ImportMapper();self::assertSame(['external_id','title','lat','lng','area'],$mapper->headers(['external id','title','lat','lng','Area']));self::assertSame([],$mapper->validateHeaders(['title','lat','lng','area']));self::assertNotContains('area_path',ImportMapper::ALLOWED_COLUMNS);}
    public function testValidAreaCreatesThenReplacesOneDirectAreaAndIndex(): void {$id=$this->import(['external_id','title','lat','lng','area'],['NEW','New','53.9','27.5','area-a'])['locationId'];self::assertSame([1],$GLOBALS['bml_test_post_terms'][$id]['bml_area']);self::assertSame([1],$GLOBALS['bml_test_relation_index_rows'][$id]['bml_area']);$this->import(['external_id','title','lat','lng','area'],['NEW','Changed','53.9','27.5','area-b']);self::assertSame([2],$GLOBALS['bml_test_post_terms'][$id]['bml_area']);self::assertSame([2],$GLOBALS['bml_test_relation_index_rows'][$id]['bml_area']);}
    public function testOmittedAndEmptyAreaPreserveUnderBothUpdatePolicies(): void {$id=$this->existing([1]);$this->import(['external_id','title','lat','lng'],['EXIST','Changed','53.9','27.5']);self::assertSame([1],$GLOBALS['bml_test_post_terms'][$id]['bml_area']);$this->import(['external_id','title','lat','lng','area'],['EXIST','Changed','53.9','27.5',''],'overwrite_mapped');self::assertSame([1],$GLOBALS['bml_test_post_terms'][$id]['bml_area']);}
    public function testInvalidParentAndInactiveAreasPreserveExistingWithoutCreation(): void {$this->existing([1]);$before=count($GLOBALS['bml_test_terms']['bml_area']);foreach(['missing'=>'bml_import_area_unknown','parent'=>'location_area_not_leaf','inactive'=>'location_area_inactive'] as $slug=>$code){$result=$this->import(['external_id','title','lat','lng','area'],['EXIST','Changed','53.9','27.5',$slug]);self::assertSame($code,$result['code']);self::assertSame([1],$GLOBALS['bml_test_post_terms'][10]['bml_area']);}self::assertCount($before,$GLOBALS['bml_test_terms']['bml_area']);}
    public function testTrustedCityAssignsAreaButUnmappedSameSlugDoesNotAdopt(): void {$id=$this->import(['external_id','title','lat','lng','city'],['TRUST','Trusted','53.9','27.5','city-a'])['locationId'];self::assertSame([1],$GLOBALS['bml_test_post_terms'][$id]['bml_area']);self::assertSame([10],$GLOBALS['bml_test_post_terms'][$id]['bml_city']);$id=$this->existing([2]);$this->import(['external_id','title','lat','lng','city'],['EXIST','Changed','53.9','27.5','minsk']);self::assertSame([2],$GLOBALS['bml_test_post_terms'][$id]['bml_area']);}
    public function testAreaCityConflictHasNoPartialAreaMutation(): void {$this->existing([1]);$conflict=$this->import(['external_id','title','lat','lng','area','city'],['EXIST','Changed','53.9','27.5','area-a','city-b']);self::assertSame('bml_conflicting_area_fields',$conflict['code']);self::assertSame([1],$GLOBALS['bml_test_post_terms'][10]['bml_area']);}
    public function testExplicitAreaAcceptsMatchingTrustedCityAndUnmappedCity(): void {$id=$this->import(['external_id','title','lat','lng','area','city'],['SAME','Same','53.9','27.5','area-a','city-a'])['locationId'];self::assertSame([1],$GLOBALS['bml_test_post_terms'][$id]['bml_area']);$id=$this->import(['external_id','title','lat','lng','area','city'],['UNMAPPED','Unmapped','53.9','27.5','area-b','minsk'])['locationId'];self::assertSame([2],$GLOBALS['bml_test_post_terms'][$id]['bml_area']);}
    public function testStaleCityProvenanceDoesNotAssignOrReplaceArea(): void {$this->existing([2]);$GLOBALS['bml_test_term_meta'][1]['_bml_migrated_from_city_term_id']=99;$this->import(['external_id','title','lat','lng','city'],['EXIST','Changed','53.9','27.5','city-a']);self::assertSame([2],$GLOBALS['bml_test_post_terms'][10]['bml_area']);}
    public function testAreaPolicySkipsPrecedeAreaValidationAndMutation(): void {$this->existing([2]);$result=$this->import(['external_id','title','lat','lng','area'],['EXIST','Changed','53.9','27.5','missing'],'create_only');self::assertSame('skipped',$result['action']);self::assertSame([2],$GLOBALS['bml_test_post_terms'][10]['bml_area']);$result=$this->import(['external_id','title','lat','lng','area'],['NEW','New','53.9','27.5','missing'],'update_only');self::assertSame('skipped',$result['action']);self::assertArrayNotHasKey(11,$GLOBALS['bml_test_posts']);}
    private function existing(array $areas): int {$post=new WP_Post();$post->ID=10;$post->post_type='bml_location';$post->post_title='Existing';$post->post_status='publish';$GLOBALS['bml_test_posts'][10]=$post;$GLOBALS['bml_test_meta'][10]=['bml_external_id'=>'EXIST'];$GLOBALS['bml_test_post_terms'][10]=['bml_area'=>$areas,'bml_category'=>[20]];return 10;}
    private function term(int $id,string $name,string $slug,int $parent=0): object{return(object)['term_id'=>$id,'name'=>$name,'slug'=>$slug,'parent'=>$parent,'count'=>0];}
    private function import(array $headers,array $row,string $policy='non_empty_only'): array {$job=new ImportJob(['headers'=>$headers,'duplicateExternalIds'=>[],'dryRun'=>false,'updatePolicy'=>$policy,'id'=>1,'processingErrors'=>0,'skipped'=>0]);return(new LocationImporter(new ImportMapper()))->importRow($row,$job);}
}
