<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
use BusinessMapLocator\Migration\{AreaMigrationService,AreaMigrationStateStore,MigrationSnapshotStore};
final class MigrationPlanningControlPlaneTest extends TestCase
{
    private string $dir;
    protected function setUp(): void { $this->dir=dirname(__DIR__).'/.planning-'.bin2hex(random_bytes(4));mkdir($this->dir,0777,true);$GLOBALS['bml_test_options']=$GLOBALS['bml_test_posts']=$GLOBALS['bml_test_post_terms']=$GLOBALS['bml_test_term_meta']=[];$city=(object)['term_id'=>1,'name'=>'Minsk','slug'=>'minsk','parent'=>0,'count'=>1];$GLOBALS['bml_test_terms']=['bml_city'=>[1=>$city],'bml_area'=>[]];$post=new WP_Post();$post->ID=7;$post->post_type='bml_location';$post->post_status='publish';$GLOBALS['bml_test_posts']=[7=>$post];$GLOBALS['bml_test_post_terms']=[7=>['bml_city'=>[1],'bml_area'=>[]]]; }
    protected function tearDown(): void { $it=new RecursiveIteratorIterator(new RecursiveDirectoryIterator($this->dir,FilesystemIterator::SKIP_DOTS),RecursiveIteratorIterator::CHILD_FIRST);foreach($it as $item)$item->isDir()?rmdir($item->getPathname()):unlink($item->getPathname());rmdir($this->dir); }
    private function service(): array { $state=new AreaMigrationStateStore();return [new AreaMigrationService(new MigrationSnapshotStore($this->dir.'/snap'),null,$state),$state]; }
    public function testInspectSnapshotSimulateReachesReadyWithoutExecution(): void { [$service,$state]=$this->service();$run=$service->startInspectionRun();$this->assertSame(AreaMigrationStateStore::INSPECTED,$run['state']);$run=$service->snapshotRun($run['run_id']);$this->assertSame(AreaMigrationStateStore::SNAPSHOTTED,$run['state']);$this->assertNotEmpty($run['snapshot_path']);$run=$service->simulateRun($run['run_id']);$this->assertSame(AreaMigrationStateStore::READY,$run['state']);$this->assertSame([1],$GLOBALS['bml_test_post_terms'][7]['bml_city']);$this->assertSame([],$GLOBALS['bml_test_post_terms'][7]['bml_area']); }
    public function testSimulationBlocksWhenPlannerFindsCollision(): void { $GLOBALS['bml_test_terms']['bml_area'][2]=(object)['term_id'=>2,'name'=>'Minsk','slug'=>'minsk','parent'=>0,'count'=>0];[$service]=$this->service();$run=$service->startInspectionRun();$run=$service->snapshotRun($run['run_id']);$run=$service->simulateRun($run['run_id']);$this->assertSame(AreaMigrationStateStore::BLOCKED,$run['state']); }
    public function testSnapshotAndSimulateRejectInvalidStates(): void { [$service]=$this->service();$run=$service->startInspectionRun();$this->expectException(LogicException::class);$service->simulateRun($run['run_id']); }
    public function testPageAndActionStayNonDestructiveAndGuardPostRequests(): void { $page=file_get_contents(dirname(__DIR__).'/src/Admin/Migration/MigrationControlPage.php');$action=file_get_contents(dirname(__DIR__).'/src/Admin/Migration/Action/MigrationPlanningAction.php');foreach(['executeRelationshipPhase(','executeRollback(','resumePartial'] as $forbidden)$this->assertStringNotContainsString($forbidden,$page);$this->assertStringContainsString('current_user_can(Capabilities::MANAGE_SETTINGS)',$action);$this->assertStringContainsString("check_admin_referer('bml_migration_planning_' . \$operation)",$action);$this->assertStringContainsString("['inspect', 'snapshot', 'simulate']",$action); }
}
